version: "3.9"

services:
    database:
        image: postgres
        container_name: starter_database
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=starter
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: starter
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
